# client1_task.yaml 示例

data:
  train_data_path: /path/to/client1/train/data  
  validation_data_path: /path/to/client1/validation/data  
  test_data_path: /path/to/client2/test/data  

model:
  model_type: resnet  
  num_classes: 2     
  input_channels: 3   

train:
  epochs: 50                
  batch_size: 32            
  learning_rate: 0.001      
  optimizer: adam           
  loss_function: cross_entropy 

output:
  model_checkpoint: /path/to/client1/model/checkpoints  
  logs: /path/to/client1/training/logs  